import type { Meta, StoryObj } from '@storybook/react';
import SalesforceSearch from './salesforce-search';

const meta = {
  title: 'Components/Form/Salesforce Search',
  component: SalesforceSearch,
  tags: ['autodocs'],
} satisfies Meta<typeof SalesforceSearch>;

export default meta;
type Story = StoryObj<typeof meta>;

const partnerServicesOptions = [
  { value: 'any', label: 'All Partners' },
  { value: 'ASPS', label: 'Accredited Services Partner (ASPS)' },
  { value: 'ATC', label: 'Authorized Training Center (ATC)' },
  { value: 'MSPS', label: 'Managed Services Provider (MSPS)' },
  { value: 'GSPS', label: 'Global Service Partner (GSPS)' },
];

const provinces = [
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming',
  'District of Columbia',
  'American Samoa',
  'Guam',
  'Northern Mariana Islands',
  'Puerto Rico',
  'United States Minor Outlying Islands',
  'Virgin Islands, U.S.',
];

const stateProvinceOptions = [
  { value: 'none', label: 'Any' },
  ...provinces.map((state) => ({
    value: state,
    label: state,
  })),
];

const countries = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia, Plurinational State of',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei Darussalam',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cayman Islands',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Congo, the Democratic Republic of the',
  'Congo',
  'Cook Islands',
  'Costa Rica',
  "Cote d'Ivoire",
  'Croatia',
  'Curacao',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Ethiopia',
  'Falkland Islands (Malvinas)',
  'Faroe Islands',
  'Fiji',
  'Finland',
  'France',
  'French Polynesia',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guinea-Bissau',
  'Guinea',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Ivory Coast',
  'Jamaica',
  'Japan',
  'Jersey',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Korea, Republic of',
  'Kosovo',
  'Kuwait',
  'Kyrgyzstan',
  "Lao People's Democratic Republic",
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macao',
  'Macedonia, the former Yugoslav Republic of',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Martinique',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia, Federated States of',
  'Moldova, Republic of',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nepal',
  'Netherlands',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Norway',
  'Oman',
  'Pakistan',
  'Palestinian Territory, occupied',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Reunion',
  'Romania',
  'Russian Federation',
  'Rwanda',
  'Saint Helena',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Suriname',
  'Swaziland',
  'Sweden',
  'Switzerland',
  'Taiwan',
  'Tajikistan',
  'Tanzania, United Republic of',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks and Caicos Islands',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela, Bolivarian Republic of',
  'Viet Nam',
  'Virgin Islands, British',
  'Virgin Islands, U.S.',
  'Yemen',
  'Zambia',
  'Zimbabwe',
];

const countryOptions = [
  { value: 'none', label: 'Any' },
  ...countries.map((country) => ({
    value: country,
    label: country,
  })),
];

export const Distributor: Story = {
  args: {
    inputLabel: 'Partner Company Name',
    inputPlaceholder: 'Enter Partner Company Name',
    inputName: 'company_name',
    stateProvinceSelectName: 'state_province',
    stateProvinceSelectLabel: 'State/Province',
    stateProvinceOptions,
    stateProvinceSelectValue: 'none',
    countrySelectName: 'country',
    countrySelectLabel: 'Country',
    countryOptions,
    countrySelectValue: 'United States',
    showStatesForCountry: 'United States',
    className: 'max-w-screen-xl p-lg',
  },
};

export const Partner: Story = {
  args: {
    inputLabel: 'Partner Company Name',
    inputPlaceholder: 'Enter Partner Company Name',
    inputName: 'company_name',
    partnerServicesSelectName: 'partner_services',
    partnerServicesSelectLabel: 'Partner Services',
    partnerServicesOptions,
    partnerServicesSelectValue: 'any',
    stateProvinceSelectName: 'state_province',
    stateProvinceSelectLabel: 'State/Province',
    stateProvinceOptions,
    stateProvinceSelectValue: 'none',
    countrySelectName: 'country',
    countrySelectLabel: 'Country',
    countryOptions,
    countrySelectValue: 'United States',
    showStatesForCountry: 'United States',
    className: 'max-w-screen-xl p-lg',
  },
};
